### PR TITLE
Feature/deployed dag endpoints

### PR DESCRIPTION
**Pull request by ggsdc**

### CODE REVIEW

**Review by marioncottard — COMMENTED** [review]
It seems good to me, but shouldn't you add unit tests for the new endpoint?

**Comment by ggsdc** [comment]
> It seems good to me, but shouldn't you add unit tests for the new endpoint?

You are right, I will add them asap

**Comment by ggsdc** [comment]
@marioncottard I added the unit tests. Could you review again?

**Comment by marioncottard** [comment]
@ggsdc Yes I'm on it right now

**Review by marioncottard — APPROVED** [review]

**Pull request merged**
